<?php
// -- main options -- configurable via zoomsounds > main options
return         array(
  'embed_prettyphoto' => 'on',
  'embed_masonry' => 'on',
  'is_safebinding' => 'on',
  'use_api_caching' => 'on',
  'debug_mode' => 'off',
  'try_to_cache_total_time' => 'on',
  'dzsap_purchase_code_binded' => 'off',
  'dzsap_purchase_code' => '',
  'extra_css' => '',
  'track_downloads' => 'off',
  'show_only_published' => 'off',
  'analytics_table_created' => 'off',
  'extra_js' => '',
  'js_init_timeout' => '',
  'download_link_links_directly_to_file' => 'off',
  'force_autoplay_when_coming_from_share_link' => 'off',
  'replace_playlist_shortcode' => 'off',
  'replace_audio_shortcode' => 'off',
  'replace_audio_shortcode_extra_args' => '',
  'replace_audio_shortcode_play_in_footer' => 'off',
  'fontawesome_load_local' => 'off',
  'replace_powerpress_plugin' => 'off',
  'powerpress_read_category_xml' => 'off',
  'pcm_data_try_to_generate' => 'on',
  'enable_global_footer_player' => 'off',
  'exclude_from_search' => 'off',
  'player_pause_method' => 'pause',
  'skinwave_wave_mode' => 'canvas',
  'skinwave_wave_mode_canvas_reflection_size' => '0.25',
  'skinwave_wave_mode_canvas_waves_number' => '3',
  'skinwave_wave_mode_canvas_waves_padding' => '1',
  'skinwave_wave_mode_canvas_normalize' => 'on',
  'allow_download_only_for_registered_users' => 'off',
  'allow_download_only_for_registered_users_capability' => 'read',
  'admin_close_otheritems' => 'on',
  'force_file_get_contents' => 'off',
  'dzsap_items_hide' => 'off',
  'pcm_notice' => 'off',
  'notice_no_media' => 'on',
  'wpdb_enable' => 'off',
  'color_waveformbg' => '111111', //==no hash
  'color_waveformprog' => 'ef6b13',
  'settings_wavestyle' => 'reflect',
  'soundcloud_api_key' => '',
  'script_init_method' => 'javascript_safe',
  'wc_single_product_player' => 'off',
  'wc_single_product_player_shortcode' => '',
  'dzsaap_buddypress_player_shortcode' => '',
  'wc_loop_product_player' => 'off',
  'wc_loop_player_position__overlay__wrapper_selector' => '',
  'wc_product_play_in_footer' => 'off',
  'try_to_hide_url' => 'off',
  'sample_time_pseudo' => '',
  'wc_single_player_position' => 'top',
  'wc_loop_player_position' => 'top',
  'play_remember_time' => '120',
  'activate_comments_widget' => 'off',
  'settings_trigger_resize' => 'off',
  'wavesurfer_pcm_length' => '200',
  'mobile_disable_footer_player' => 'off',
  'enable_raw_shortcode' => 'off',
  'developer_check_for_bots_and_dont_reveal_source' => 'off',
  'enable_auto_backup' => 'on',
  'enable_aux_buttons' => 'on',
  'aws_enable_support' => 'off',
  'aws_key' => '',
  'aws_key_secret' => '',
  'aws_region' => '',
  'aws_bucket' => '',
  'dzsap_meta_post_types' => array('dzsap_items'),
  'www_handle' => 'default',
  'str_likes_part1' => '<span class="btn-zoomsounds btn-like"><span class="the-icon">{{heart_svg}}</span><span class="the-label hide-on-active">Like</span><span class="the-label show-on-active">Liked</span></span>',
  'str_views' => '<div class="dzsap-counter counter-hits"><i class="fa fa-play"></i><span class="the-number">{{get_plays}}</span></div>',
  'str_downloads_counter' => '<div class="dzsap-counter counter-downloads"><i class="fa fa-cloud-download"></i><span class="the-number">{{get_downloads}}</span></div>',
  'str_likes_part2' => '<div class="dzsap-counter counter-likes"><i class="fa fa-heart"></i><span class="the-number">{{get_likes}}</span></div>',
  'str_rates' => '<div class="dzsap-counter counter-rates"><span class="the-number">{{get_rates}}</span> rates</div>',
  'waveformgenerator_multiplier' => '1',
  'always_embed' => 'off',
  'single_index_seo_disable' => 'off',
  'loop_playlist' => 'on',
  'try_to_get_id3_thumb_in_frontend' => 'off',
  'failsafe_repair_media_element' => 'off',
  'construct_player_list_for_sync' => 'off',
  'i18n_buy' => '',
  'i18n_play' => '',
  'i18n_title' => '',
  'i18n_free_download' => esc_html__("Free Download"),
  'i18n_register_to_download' => '',
  'register_to_download_opens_in_new_link' => 'off',
  'analytics_enable' => 'off',
  'analytics_enable_location' => 'off',
  'analytics_enable_user_track' => 'off',

  'keyboard_show_tooltips' => 'off',
  'keyboard_play_trigger_step_back' => 'off',
  'keyboard_step_back_amount' => '5',
  'keyboard_step_back' => '37',
  'keyboard_step_forward' => '39',
  'keyboard_pause_play' => '32',
  'keyboard_sync_players_goto_prev' => '',
  'keyboard_sync_players_goto_next' => '',

  'analytics_galleries' => '', // -- deprecated

  'admin_nag_disable_all' => '',

  // -- portal
  'dzsapp_bp_player_config' => 'sample--skin-wave--with-comments',
  'dzsapp_single_show_views' => 'on',
  'dzsapp_enable_tab_playlist' => 'on',
  'dzsapp_tab_share_content' => '<span class="share-icon-active"><iframe src="//www.facebook.com/plugins/like.php?href={{currurl}}&width&layout=button_count&action=like&show_faces=false&share=false&height=21&appId=569360426428348" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:21px;" allowTransparency="true"></iframe></span><h5>Embed</h5><div class="dzsapp-code">{{embedcode}}</div>',

  'dzsaap_enable_youtube' => 'off',
  'dzsaap_enable_unregistered_submit' => 'off',
  'dzsaap_disable_self_hosted_audio_upload' => 'off',
  'dzsaap_default_portal_upload_type' => 'audio',
  'dzsaap_redirect_url_after_submission' => '{{newtrack}}',
  'dzsapp_video_item_show_meta' => 'on',
  'dzsapp_player_shortcode' => '',
  'dzsapp_video_item_show_meta_only_in_single' => 'on',
  'dzsaap_default_thumbnail_image' => 'https://via.placeholder.com/150',
);