(function(){var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function $$jscomp$createTemplateTagFirstArg$(arrayStrings){return arrayStrings.raw=arrayStrings};$jscomp.createTemplateTagFirstArgWithRaw=function $$jscomp$createTemplateTagFirstArgWithRaw$(arrayStrings,rawArrayStrings){arrayStrings.raw=rawArrayStrings;return arrayStrings};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(target,property,descriptor){if(target==Array.prototype||target==Object.prototype)return target;target[property]=descriptor.value;return target};
$jscomp.getGlobal=function $$jscomp$getGlobal$(passedInThis_possibleGlobals){passedInThis_possibleGlobals=["object"==typeof globalThis&&globalThis,passedInThis_possibleGlobals,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var i=0;i<passedInThis_possibleGlobals.length;++i){var maybeGlobal=passedInThis_possibleGlobals[i];if(maybeGlobal&&maybeGlobal.Math==Math)return maybeGlobal}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";
var $jscomp$lookupPolyfilledValue=function $$jscomp$lookupPolyfilledValue$(target,key){var polyfill_polyfilledKey=$jscomp.propertyToPolyfillSymbol[key];if(null==polyfill_polyfilledKey)return target[key];polyfill_polyfilledKey=target[polyfill_polyfilledKey];return void 0!==polyfill_polyfilledKey?polyfill_polyfilledKey:target[key]};
$jscomp.polyfill=function $$jscomp$polyfill$(target,polyfill,fromLang,toLang){polyfill&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(target,polyfill,fromLang,toLang):$jscomp.polyfillUnisolated(target,polyfill,fromLang,toLang))};
$jscomp.polyfillUnisolated=function $$jscomp$polyfillUnisolated$(property$jscomp$5_split_target,impl_polyfill,fromLang$jscomp$1_obj,i$jscomp$4_orig_toLang){fromLang$jscomp$1_obj=$jscomp.global;property$jscomp$5_split_target=property$jscomp$5_split_target.split(".");for(i$jscomp$4_orig_toLang=0;i$jscomp$4_orig_toLang<property$jscomp$5_split_target.length-1;i$jscomp$4_orig_toLang++){var key=property$jscomp$5_split_target[i$jscomp$4_orig_toLang];if(!(key in fromLang$jscomp$1_obj))return;fromLang$jscomp$1_obj=
fromLang$jscomp$1_obj[key]}property$jscomp$5_split_target=property$jscomp$5_split_target[property$jscomp$5_split_target.length-1];i$jscomp$4_orig_toLang=fromLang$jscomp$1_obj[property$jscomp$5_split_target];impl_polyfill=impl_polyfill(i$jscomp$4_orig_toLang);impl_polyfill!=i$jscomp$4_orig_toLang&&null!=impl_polyfill&&$jscomp.defineProperty(fromLang$jscomp$1_obj,property$jscomp$5_split_target,{configurable:!0,writable:!0,value:impl_polyfill})};
$jscomp.polyfillIsolated=function $$jscomp$polyfillIsolated$(isNativeClass_target,impl$jscomp$1_polyfill,fromLang,obj$jscomp$27_root$jscomp$3_toLang){var property$jscomp$6_split=isNativeClass_target.split(".");isNativeClass_target=1===property$jscomp$6_split.length;obj$jscomp$27_root$jscomp$3_toLang=property$jscomp$6_split[0];obj$jscomp$27_root$jscomp$3_toLang=!isNativeClass_target&&obj$jscomp$27_root$jscomp$3_toLang in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var i=0;i<property$jscomp$6_split.length-
1;i++){var key=property$jscomp$6_split[i];if(!(key in obj$jscomp$27_root$jscomp$3_toLang))return;obj$jscomp$27_root$jscomp$3_toLang=obj$jscomp$27_root$jscomp$3_toLang[key]}property$jscomp$6_split=property$jscomp$6_split[property$jscomp$6_split.length-1];fromLang=$jscomp.IS_SYMBOL_NATIVE&&"es6"===fromLang?obj$jscomp$27_root$jscomp$3_toLang[property$jscomp$6_split]:null;impl$jscomp$1_polyfill=impl$jscomp$1_polyfill(fromLang);null!=impl$jscomp$1_polyfill&&(isNativeClass_target?$jscomp.defineProperty($jscomp.polyfills,
property$jscomp$6_split,{configurable:!0,writable:!0,value:impl$jscomp$1_polyfill}):impl$jscomp$1_polyfill!==fromLang&&($jscomp.propertyToPolyfillSymbol[property$jscomp$6_split]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(property$jscomp$6_split):$jscomp.POLYFILL_PREFIX+property$jscomp$6_split,property$jscomp$6_split=$jscomp.propertyToPolyfillSymbol[property$jscomp$6_split],$jscomp.defineProperty(obj$jscomp$27_root$jscomp$3_toLang,property$jscomp$6_split,{configurable:!0,writable:!0,value:impl$jscomp$1_polyfill})))};
$jscomp.underscoreProtoCanBeSet=function $$jscomp$underscoreProtoCanBeSet$(){var x={a:!0},y={};try{return y.__proto__=x,y.a}catch(e){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(target,proto){target.__proto__=proto;if(target.__proto__!==proto)throw new TypeError(target+" is not extensible");return target}:null;
$jscomp.arrayIteratorImpl=function $$jscomp$arrayIteratorImpl$(array){var index=0;return function(){return index<array.length?{done:!1,value:array[index++]}:{done:!0}}};$jscomp.arrayIterator=function $$jscomp$arrayIterator$(array){return{next:$jscomp.arrayIteratorImpl(array)}};$jscomp.makeIterator=function $$jscomp$makeIterator$(iterable){var iteratorFunction="undefined"!=typeof Symbol&&Symbol.iterator&&iterable[Symbol.iterator];return iteratorFunction?iteratorFunction.call(iterable):$jscomp.arrayIterator(iterable)};
$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function $$jscomp$generator$ensureIteratorResultIsObject_$(result){if(!(result instanceof Object))throw new TypeError("Iterator result "+result+" is not an object");};$jscomp.generator.Context=function $$jscomp$generator$Context$(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function $$jscomp$generator$Context$$start_$(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function $$jscomp$generator$Context$$stop_$(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function $$jscomp$generator$Context$$jumpToErrorHandler_$(){this.nextAddress=this.catchAddress_||this.finallyAddress_};
$jscomp.generator.Context.prototype.next_=function $$jscomp$generator$Context$$next_$(value){this.yieldResult=value};$jscomp.generator.Context.prototype.throw_=function $$jscomp$generator$Context$$throw_$(e){this.abruptCompletion_={exception:e,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function $$jscomp$generator$Context$$return$(value){this.abruptCompletion_={return:value};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function $$jscomp$generator$Context$$jumpThroughFinallyBlocks$(nextAddress){this.abruptCompletion_={jumpTo:nextAddress};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function $$jscomp$generator$Context$$yield$(value,resumeAddress){this.nextAddress=resumeAddress;return{value:value}};
$jscomp.generator.Context.prototype.yieldAll=function $$jscomp$generator$Context$$yieldAll$(iterable$jscomp$4_iterator,resumeAddress){iterable$jscomp$4_iterator=$jscomp.makeIterator(iterable$jscomp$4_iterator);var result=iterable$jscomp$4_iterator.next();$jscomp.generator.ensureIteratorResultIsObject_(result);if(result.done)this.yieldResult=result.value,this.nextAddress=resumeAddress;else return this.yieldAllIterator_=iterable$jscomp$4_iterator,this.yield(result.value,resumeAddress)};
$jscomp.generator.Context.prototype.jumpTo=function $$jscomp$generator$Context$$jumpTo$(nextAddress){this.nextAddress=nextAddress};$jscomp.generator.Context.prototype.jumpToEnd=function $$jscomp$generator$Context$$jumpToEnd$(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function $$jscomp$generator$Context$$setCatchFinallyBlocks$(catchAddress,finallyAddress){this.catchAddress_=catchAddress;void 0!=finallyAddress&&(this.finallyAddress_=finallyAddress)};
$jscomp.generator.Context.prototype.setFinallyBlock=function $$jscomp$generator$Context$$setFinallyBlock$(finallyAddress){this.catchAddress_=0;this.finallyAddress_=finallyAddress||0};$jscomp.generator.Context.prototype.leaveTryBlock=function $$jscomp$generator$Context$$leaveTryBlock$(nextAddress,catchAddress){this.nextAddress=nextAddress;this.catchAddress_=catchAddress||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function $$jscomp$generator$Context$$enterCatchBlock$(exception){this.catchAddress_=exception||0;exception=this.abruptCompletion_.exception;this.abruptCompletion_=null;return exception};
$jscomp.generator.Context.prototype.enterFinallyBlock=function $$jscomp$generator$Context$$enterFinallyBlock$(nextCatchAddress,nextFinallyAddress,finallyDepth){finallyDepth?this.finallyContexts_[finallyDepth]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=nextCatchAddress||0;this.finallyAddress_=nextFinallyAddress||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function $$jscomp$generator$Context$$leaveFinallyBlock$(nextAddress,abruptCompletion_finallyDepth){abruptCompletion_finallyDepth=this.finallyContexts_.splice(abruptCompletion_finallyDepth||0)[0];if(abruptCompletion_finallyDepth=this.abruptCompletion_=this.abruptCompletion_||abruptCompletion_finallyDepth){if(abruptCompletion_finallyDepth.isException)return this.jumpToErrorHandler_();void 0!=abruptCompletion_finallyDepth.jumpTo&&this.finallyAddress_<
abruptCompletion_finallyDepth.jumpTo?(this.nextAddress=abruptCompletion_finallyDepth.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=nextAddress};$jscomp.generator.Context.prototype.forIn=function $$jscomp$generator$Context$$forIn$(object){return new $jscomp.generator.Context.PropertyIterator(object)};
$jscomp.generator.Context.PropertyIterator=function $$jscomp$generator$Context$PropertyIterator$(object){this.object_=object;this.properties_=[];for(var property in object)this.properties_.push(property);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function $$jscomp$generator$Context$PropertyIterator$$getNext$(){for(;0<this.properties_.length;){var property=this.properties_.pop();if(property in this.object_)return property}return null};
$jscomp.generator.Engine_=function $$jscomp$generator$Engine_$(program){this.context_=new $jscomp.generator.Context;this.program_=program};$jscomp.generator.Engine_.prototype.next_=function $$jscomp$generator$Engine_$$next_$(value){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,value,this.context_.next_);this.context_.next_(value);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function $$jscomp$generator$Engine_$$return_$(value){this.context_.start_();var yieldAllIterator=this.context_.yieldAllIterator_;if(yieldAllIterator)return this.yieldAllStep_("return"in yieldAllIterator?yieldAllIterator["return"]:function(v){return{value:v,done:!0}},value,this.context_.return);this.context_.return(value);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function $$jscomp$generator$Engine_$$throw_$(exception){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],exception,this.context_.next_);this.context_.throw_(exception);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function $$jscomp$generator$Engine_$$yieldAllStep_$(action,value,nextAction){try{var result=action.call(this.context_.yieldAllIterator_,value);$jscomp.generator.ensureIteratorResultIsObject_(result);if(!result.done)return this.context_.stop_(),result;var resultValue=result.value}catch(e){return this.context_.yieldAllIterator_=null,this.context_.throw_(e),this.nextStep_()}this.context_.yieldAllIterator_=null;nextAction.call(this.context_,resultValue);
return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function $$jscomp$generator$Engine_$$nextStep_$(){for(;this.context_.nextAddress;)try{var abruptCompletion=this.program_(this.context_);if(abruptCompletion)return this.context_.stop_(),{value:abruptCompletion.value,done:!1}}catch(e){this.context_.yieldResult=void 0,this.context_.throw_(e)}this.context_.stop_();if(this.context_.abruptCompletion_){abruptCompletion=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(abruptCompletion.isException)throw abruptCompletion.exception;
return{value:abruptCompletion.return,done:!0}}return{value:void 0,done:!0}};$jscomp.generator.Generator_=function $$jscomp$generator$Generator_$(engine){this.next=function $this$next$(opt_value){return engine.next_(opt_value)};this.throw=function $this$throw$(exception){return engine.throw_(exception)};this.return=function $this$return$(value){return engine.return_(value)};this[Symbol.iterator]=function $this$Symbol$iterator$(){return this}};
$jscomp.generator.createGenerator=function $$jscomp$generator$createGenerator$(generator,program$jscomp$64_result){program$jscomp$64_result=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(program$jscomp$64_result));$jscomp.setPrototypeOf&&generator.prototype&&$jscomp.setPrototypeOf(program$jscomp$64_result,generator.prototype);return program$jscomp$64_result};
$jscomp.asyncExecutePromiseGenerator=function $$jscomp$asyncExecutePromiseGenerator$(generator){function passValueToGenerator(value){return generator.next(value)}function passErrorToGenerator(error){return generator.throw(error)}return new Promise(function(resolve,reject){function handleGeneratorRecord(genRec){genRec.done?resolve(genRec.value):Promise.resolve(genRec.value).then(passValueToGenerator,passErrorToGenerator).then(handleGeneratorRecord,reject)}handleGeneratorRecord(generator.next())})};
$jscomp.asyncExecutePromiseGeneratorFunction=function $$jscomp$asyncExecutePromiseGeneratorFunction$(generatorFunction){return $jscomp.asyncExecutePromiseGenerator(generatorFunction())};$jscomp.asyncExecutePromiseGeneratorProgram=function $$jscomp$asyncExecutePromiseGeneratorProgram$(program){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(program)))};$jscomp.initSymbol=function $$jscomp$initSymbol$(){};
$jscomp.polyfill("Symbol",function(orig){if(orig)return orig;var SymbolClass=function $SymbolClass$(id,opt_description){this.$jscomp$symbol$id_=id;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:opt_description})};SymbolClass.prototype.toString=function $SymbolClass$$toString$(){return this.$jscomp$symbol$id_};var counter=0,symbolPolyfill=function $symbolPolyfill$(opt_description){if(this instanceof symbolPolyfill)throw new TypeError("Symbol is not a constructor");return new SymbolClass("jscomp_symbol_"+
(opt_description||"")+"_"+counter++,opt_description)};return symbolPolyfill},"es6","es3");$jscomp.initSymbolIterator=function $$jscomp$initSymbolIterator$(){};
$jscomp.polyfill("Symbol.iterator",function(orig){if(orig)return orig;orig=Symbol("Symbol.iterator");for(var arrayLikes="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),i=0;i<arrayLikes.length;i++){var ArrayLikeCtor=$jscomp.global[arrayLikes[i]];"function"===typeof ArrayLikeCtor&&"function"!=typeof ArrayLikeCtor.prototype[orig]&&$jscomp.defineProperty(ArrayLikeCtor.prototype,orig,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return orig},
"es6","es3");$jscomp.initSymbolAsyncIterator=function $$jscomp$initSymbolAsyncIterator$(){};$jscomp.iteratorPrototype=function $$jscomp$iteratorPrototype$(iterator){iterator={next:iterator};iterator[Symbol.iterator]=function $iterator$Symbol$iterator$(){return this};return iterator};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(NativePromise){function AsyncExecutor(){this.batch_=null}function resolvingPromise(opt_value){return opt_value instanceof PolyfillPromise?opt_value:new PolyfillPromise(function(resolve,reject){resolve(opt_value)})}if(NativePromise&&!$jscomp.FORCE_POLYFILL_PROMISE)return NativePromise;AsyncExecutor.prototype.asyncExecute=function $AsyncExecutor$$asyncExecute$(f){if(null==this.batch_){this.batch_=[];var self=this;this.asyncExecuteFunction(function(){self.executeBatch_()})}this.batch_.push(f)};
var nativeSetTimeout=$jscomp.global.setTimeout;AsyncExecutor.prototype.asyncExecuteFunction=function $AsyncExecutor$$asyncExecuteFunction$(f){nativeSetTimeout(f,0)};AsyncExecutor.prototype.executeBatch_=function $AsyncExecutor$$executeBatch_$(){for(;this.batch_&&this.batch_.length;){var executingBatch=this.batch_;this.batch_=[];for(var i=0;i<executingBatch.length;++i){var f=executingBatch[i];executingBatch[i]=null;try{f()}catch(error){this.asyncThrow_(error)}}}this.batch_=null};AsyncExecutor.prototype.asyncThrow_=
function $AsyncExecutor$$asyncThrow_$(exception){this.asyncExecuteFunction(function(){throw exception;})};var PolyfillPromise=function $PolyfillPromise$(executor){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var resolveAndReject=this.createResolveAndReject_();try{executor(resolveAndReject.resolve,resolveAndReject.reject)}catch(e){resolveAndReject.reject(e)}};PolyfillPromise.prototype.createResolveAndReject_=function $PolyfillPromise$$createResolveAndReject_$(){function firstCallWins(method){return function(x){alreadyCalled||
(alreadyCalled=!0,method.call(thisPromise,x))}}var thisPromise=this,alreadyCalled=!1;return{resolve:firstCallWins(this.resolveTo_),reject:firstCallWins(this.reject_)}};PolyfillPromise.prototype.resolveTo_=function $PolyfillPromise$$resolveTo_$(value){if(value===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(value instanceof PolyfillPromise)this.settleSameAsPromise_(value);else{a:switch(typeof value){case "object":var JSCompiler_inline_result=null!=value;break a;case "function":JSCompiler_inline_result=
!0;break a;default:JSCompiler_inline_result=!1}JSCompiler_inline_result?this.resolveToNonPromiseObj_(value):this.fulfill_(value)}};PolyfillPromise.prototype.resolveToNonPromiseObj_=function $PolyfillPromise$$resolveToNonPromiseObj_$(obj){var thenMethod=void 0;try{thenMethod=obj.then}catch(error){this.reject_(error);return}"function"==typeof thenMethod?this.settleSameAsThenable_(thenMethod,obj):this.fulfill_(obj)};PolyfillPromise.prototype.reject_=function $PolyfillPromise$$reject_$(reason){this.settle_(2,
reason)};PolyfillPromise.prototype.fulfill_=function $PolyfillPromise$$fulfill_$(value){this.settle_(1,value)};PolyfillPromise.prototype.settle_=function $PolyfillPromise$$settle_$(settledState,valueOrReason){if(0!=this.state_)throw Error("Cannot settle("+settledState+", "+valueOrReason+"): Promise already settled in state"+this.state_);this.state_=settledState;this.result_=valueOrReason;this.executeOnSettledCallbacks_()};PolyfillPromise.prototype.executeOnSettledCallbacks_=function $PolyfillPromise$$executeOnSettledCallbacks_$(){if(null!=
this.onSettledCallbacks_){for(var i=0;i<this.onSettledCallbacks_.length;++i)asyncExecutor.asyncExecute(this.onSettledCallbacks_[i]);this.onSettledCallbacks_=null}};var asyncExecutor=new AsyncExecutor;PolyfillPromise.prototype.settleSameAsPromise_=function $PolyfillPromise$$settleSameAsPromise_$(promise){var methods=this.createResolveAndReject_();promise.callWhenSettled_(methods.resolve,methods.reject)};PolyfillPromise.prototype.settleSameAsThenable_=function $PolyfillPromise$$settleSameAsThenable_$(thenMethod,
thenable){var methods=this.createResolveAndReject_();try{thenMethod.call(thenable,methods.resolve,methods.reject)}catch(error){methods.reject(error)}};PolyfillPromise.prototype.then=function $PolyfillPromise$$then$(onFulfilled,onRejected){function createCallback(paramF,defaultF){return"function"==typeof paramF?function(x){try{resolveChild(paramF(x))}catch(error){rejectChild(error)}}:defaultF}var resolveChild,rejectChild,childPromise=new PolyfillPromise(function(resolve,reject){resolveChild=resolve;
rejectChild=reject});this.callWhenSettled_(createCallback(onFulfilled,resolveChild),createCallback(onRejected,rejectChild));return childPromise};PolyfillPromise.prototype.catch=function $PolyfillPromise$$catch$(onRejected){return this.then(void 0,onRejected)};PolyfillPromise.prototype.callWhenSettled_=function $PolyfillPromise$$callWhenSettled_$(onFulfilled,onRejected){function callback(){switch(thisPromise.state_){case 1:onFulfilled(thisPromise.result_);break;case 2:onRejected(thisPromise.result_);
break;default:throw Error("Unexpected state: "+thisPromise.state_);}}var thisPromise=this;null==this.onSettledCallbacks_?asyncExecutor.asyncExecute(callback):this.onSettledCallbacks_.push(callback)};PolyfillPromise.resolve=resolvingPromise;PolyfillPromise.reject=function $PolyfillPromise$reject$(opt_reason){return new PolyfillPromise(function(resolve,reject){reject(opt_reason)})};PolyfillPromise.race=function $PolyfillPromise$race$(thenablesOrValues){return new PolyfillPromise(function(resolve,reject){for(var iterator=
$jscomp.makeIterator(thenablesOrValues),iterRec=iterator.next();!iterRec.done;iterRec=iterator.next())resolvingPromise(iterRec.value).callWhenSettled_(resolve,reject)})};PolyfillPromise.all=function $PolyfillPromise$all$(thenablesOrValues){var iterator=$jscomp.makeIterator(thenablesOrValues),iterRec=iterator.next();return iterRec.done?resolvingPromise([]):new PolyfillPromise(function(resolveAll,rejectAll){function onFulfilled(i){return function(ithResult){resultsArray[i]=ithResult;unresolvedCount--;
0==unresolvedCount&&resolveAll(resultsArray)}}var resultsArray=[],unresolvedCount=0;do resultsArray.push(void 0),unresolvedCount++,resolvingPromise(iterRec.value).callWhenSettled_(onFulfilled(resultsArray.length-1),rejectAll),iterRec=iterator.next();while(!iterRec.done)})};return PolyfillPromise},"es6","es3");
$jscomp.iteratorFromArray=function $$jscomp$iteratorFromArray$(array,transform){array instanceof String&&(array+="");var i=0,iter={next:function(){if(i<array.length){var index=i++;return{value:transform(index,array[index]),done:!1}}iter.next=function $iter$next$(){return{done:!0,value:void 0}};return iter.next()}};iter[Symbol.iterator]=function $iter$Symbol$iterator$(){return iter};return iter};
$jscomp.polyfill("Array.prototype.keys",function(orig){return orig?orig:function(){return $jscomp.iteratorFromArray(this,function(i){return i})}},"es6","es3");$jscomp.owns=function $$jscomp$owns$(obj,prop){return Object.prototype.hasOwnProperty.call(obj,prop)};
$jscomp.assign=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.assign?Object.assign:function(target,var_args){for(var i=1;i<arguments.length;i++){var source=arguments[i];if(source)for(var key in source)$jscomp.owns(source,key)&&(target[key]=source[key])}return target};$jscomp.polyfill("Object.assign",function(orig){return orig||$jscomp.assign},"es6","es3");
$jscomp.findInternal=function $$jscomp$findInternal$(array,callback,thisArg){array instanceof String&&(array=String(array));for(var len=array.length,i=0;i<len;i++){var value=array[i];if(callback.call(thisArg,value,i,array))return{i:i,v:value}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(orig){return orig?orig:function(callback,opt_thisArg){return $jscomp.findInternal(this,callback,opt_thisArg).v}},"es6","es3");
(function(){function __webpack_require__(moduleId){if(__webpack_module_cache__[moduleId])return __webpack_module_cache__[moduleId].exports;var module=__webpack_module_cache__[moduleId]={exports:{}};__webpack_modules__[moduleId](module,module.exports,__webpack_require__);return module.exports}var __webpack_modules__={567:function(__unused_webpack_module,__webpack_exports__,__webpack_require__){__webpack_require__.d(__webpack_exports__,{OF:function(){return ConstantsDzsAp},LW:function(){return"#dzsap-main-settings"},
w0:function(){return"#dzsap-keyboard-controls"}});var ConstantsDzsAp={PLAYLIST_TRANSITION_DURATION:300,DEBUG_STYLE_1:"background-color: #aaa022; color: #222222;",DEBUG_STYLE_2:"background-color: #7c3b8e; color: #ffffff;",DEBUG_STYLE_3:"background-color: #3a696b; color: #eeeeee;",DEBUG_STYLE_ERROR:"background-color: #3a696b; color: #eeeeee;",URL_WAVESURFER_HELPER_BACKUP:"https://zoomthe.me/assets/dzsap-wave-generate.js",WAVESURFER_MAX_TIMEOUT:2E4,URL_JQUERY:"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js",
DEBUG_STYLE_PLAY_FUNCTIONS:"background-color: #daffda; color: #222222;",ERRORED_OUT_CLASS:"errored-out",ERRORED_OUT_MAX_ATTEMPTS:5}},401:function(__unused_webpack_module,__webpack_exports__,__webpack_require__){__webpack_require__.d(__webpack_exports__,{JY:function(){return isValid}});var isValid=function $isValid$(n){return"undefined"!=typeof n&&""!=n}},586:function(__unused_webpack_module,__webpack_exports__,__webpack_require__){function convertPluginOptionsToFinalOptions($elThis_elThis,defaultOptions,
argOptions,aux,$es){argOptions=void 0===argOptions?null:argOptions;aux=void 0===aux?"data-options":aux;var tempOptions={},isSetFromJson=!1;void 0===$es&&($es=jQuery);$elThis_elThis=$es($elThis_elThis);if(argOptions&&"object"===typeof argOptions&&Object.keys(argOptions).length)tempOptions=argOptions;else{if($elThis_elThis.attr(aux))try{tempOptions=JSON.parse($elThis_elThis.attr(aux)),isSetFromJson=!0}catch(err){}isSetFromJson||"undefined"==typeof $elThis_elThis.attr(aux)||""==$elThis_elThis.attr("data-options")||
(aux=$elThis_elThis.attr(aux),eval("var aux_opts = "+aux),tempOptions=Object.assign({},argOptions))}return Object.assign(defaultOptions,tempOptions)}function generateFakeArrayForPcm(){for(var arr=[],it1=0;256>it1;it1++)arr[it1]=100*Math.random();return arr}__webpack_require__.d(__webpack_exports__,{convertPluginOptionsToFinalOptions:function(){return convertPluginOptionsToFinalOptions},generateFakeArrayForPcm:function(){return generateFakeArrayForPcm}});__webpack_require__(401);__webpack_require__(560);
__webpack_require__(603);__webpack_require__(567)},560:function(__unused_webpack_module,__webpack_exports__,__webpack_require__){__webpack_require__.d(__webpack_exports__,{a$:function(){return'<svg class="svg-icon" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" width="512px" height="512px" viewBox="0 0 511.626 511.627" style="enable-background:new 0 0 511.626 511.627;" xml:space="preserve"> <g> <path d="M506.206,179.012L360.025,32.834c-3.617-3.617-7.898-5.426-12.847-5.426s-9.233,1.809-12.847,5.426 c-3.617,3.619-5.428,7.902-5.428,12.85v73.089h-63.953c-135.716,0-218.984,38.354-249.823,115.06C5.042,259.335,0,291.03,0,328.907 c0,31.594,12.087,74.514,36.259,128.762c0.57,1.335,1.566,3.614,2.996,6.849c1.429,3.233,2.712,6.088,3.854,8.565 c1.146,2.471,2.384,4.565,3.715,6.276c2.282,3.237,4.948,4.859,7.994,4.859c2.855,0,5.092-0.951,6.711-2.854 c1.615-1.902,2.424-4.284,2.424-7.132c0-1.718-0.238-4.236-0.715-7.569c-0.476-3.333-0.715-5.564-0.715-6.708 c-0.953-12.938-1.429-24.653-1.429-35.114c0-19.223,1.668-36.449,4.996-51.675c3.333-15.229,7.948-28.407,13.85-39.543 c5.901-11.14,13.512-20.745,22.841-28.835c9.325-8.09,19.364-14.702,30.118-19.842c10.756-5.141,23.413-9.186,37.974-12.135 c14.56-2.95,29.215-4.997,43.968-6.14s31.455-1.711,50.109-1.711h63.953v73.091c0,4.948,1.807,9.232,5.421,12.847 c3.62,3.613,7.901,5.424,12.847,5.424c4.948,0,9.232-1.811,12.854-5.424l146.178-146.183c3.617-3.617,5.424-7.898,5.424-12.847 C511.626,186.92,509.82,182.636,506.206,179.012z" fill="#696969"/> </g></svg> '}})},
603:function(__unused_webpack_module,__webpack_exports__,__webpack_require__){function handle_keypresses(e){function isKeyPressed(checkKeyCode){var isKeyPressed=!1;-1<checkKeyCode.indexOf("ctrl+")?e.ctrlKey&&(checkKeyCode=checkKeyCode.replace("ctrl+",""),e.keyCode===Number(checkKeyCode)&&(isKeyPressed=!0)):e.keyCode===Number(checkKeyCode)&&(isKeyPressed=!0);return isKeyPressed}if(!window.dzsap_isTextFieldFocused){var $=jQuery,keyboard_controls=$.extend({},dzsap_generate_keyboard_controls());if(dzsap_currplayer_focused&&
dzsap_currplayer_focused.api_pause_media){if(isKeyPressed(keyboard_controls.pause_play)&&!$(dzsap_currplayer_focused).hasClass("comments-writer-active")&&($(dzsap_currplayer_focused).hasClass("is-playing")?dzsap_currplayer_focused.api_pause_media():dzsap_currplayer_focused.api_play_media(),window.dzsap_mouseover))return e.preventDefault(),!1;isKeyPressed(keyboard_controls.step_back)&&dzsap_currplayer_focused.api_step_back(keyboard_controls.step_back_amount);isKeyPressed(keyboard_controls.step_forward)&&
dzsap_currplayer_focused.api_step_forward(keyboard_controls.step_back_amount);isKeyPressed(keyboard_controls.sync_players_goto_next)&&dzsap_currplayer_focused.api_sync_players_goto_next();isKeyPressed(keyboard_controls.sync_players_goto_prev)&&dzsap_currplayer_focused.api_sync_players_goto_prev()}}}__webpack_require__.d(__webpack_exports__,{z2:function(){return dzsap_keyboardSetup}});var _configs_constants__WEBPACK_IMPORTED_MODULE_0__=__webpack_require__(567),dzsap_generate_keyboard_controls=function $dzsap_generate_keyboard_controls$(){var keyboard_controls=
{play_trigger_step_back:"off",step_back_amount:"5",step_back:"37",step_forward:"39",sync_players_goto_next:"",sync_players_goto_prev:"",pause_play:"32",show_tooltips:"off"},$keyboardControlsInfo=jQuery(_configs_constants__WEBPACK_IMPORTED_MODULE_0__.w0);$keyboardControlsInfo.length&&(window.dzsap_keyboard_controls=JSON.parse($keyboardControlsInfo.html()));window.dzsap_keyboard_controls&&(keyboard_controls=jQuery.extend(keyboard_controls,window.dzsap_keyboard_controls));keyboard_controls.step_back_amount=
Number(keyboard_controls.step_back_amount);return keyboard_controls},dzsap_keyboardSetup=function $dzsap_keyboardSetup$(){var $=jQuery;window.dzsap_isTextFieldFocused=!1;$(document).off("keydown.dzsapkeyup");$(document).on("keydown.dzsapkeyup",handle_keypresses);$(document).on("focus blur","textarea,input",function(e){if("focusin"==e.type||"focus"==e.type)window.dzsap_isTextFieldFocused=!0;if("focusout"==e.type||"blur"==e.type)window.dzsap_isTextFieldFocused=!1});$(document).on("keydown blur",".zoomsounds-search-field",
function(e){var _t=$(e.currentTarget);setTimeout(function(){if(_t){var $audioGallery=$(".audiogallery").eq(0);_t.attr("data-target")&&($audioGallery=$(_t.attr("data-target")));$audioGallery.get(0)&&$audioGallery.get(0).api_filter&&$audioGallery.get(0).api_filter("title",_t.val())}},100)})}}},__webpack_module_cache__={};!function(){__webpack_require__.d=function $__webpack_require__$d$(exports,definition){for(var key in definition)__webpack_require__.o(definition,key)&&!__webpack_require__.o(exports,
key)&&Object.defineProperty(exports,key,{enumerable:!0,get:definition[key]})}}();!function(){__webpack_require__.o=function $__webpack_require__$o$(obj,prop){return Object.prototype.hasOwnProperty.call(obj,prop)}}();!function(){function isNodeList(nodes){var stringRepr=Object.prototype.toString.call(nodes);return"object"===typeof nodes&&/^\[object (HTMLCollection|NodeList|Object)\]$/.test(stringRepr)&&"number"===typeof nodes.length&&(0===nodes.length||"object"===typeof nodes[0]&&0<nodes[0].nodeType)}
var _dzsap_helpers=__webpack_require__(586),esJquery=function $esJquery$(selector){var $jscomp$this=this;"string"==typeof selector?(this.$el=document.querySelector(selector),this.$els=document.querySelectorAll(selector)):(this.$el=selector,isNodeList(selector)&&(this.$el=selector[0]),this.$els=[],isNodeList(selector)?selector.forEach(function(_el){$jscomp$this.$els.push(_el)}):this.$els.push(this.$el))};esJquery.prototype.hide=function $esJquery$$hide$(){this.$els.forEach(function(el){el.style.display=
"none"})};esJquery.prototype.clone=function $esJquery$$clone$(){var cln=this.$el.cloneNode(!0);this.$el.parentNode.appendChild(cln);return cln};esJquery.prototype.show=function $esJquery$$show$(){this.$els.forEach(function(el){el.style.display=""})};esJquery.prototype.trigger=function $esJquery$$trigger$(eventType){this.$els.forEach(function(el){var event=new Event(eventType);el.dispatchEvent(event)})};esJquery.prototype.addClass=function $esJquery$$addClass$(arg){this.$els.forEach(function(el3){el3.classList.add(arg)});
return this};esJquery.prototype.removeClass=function $esJquery$$removeClass$(arg){this.$els.forEach(function(el3){el3.classList.remove(arg)});return this};esJquery.prototype.prepend=function $esJquery$$prepend$(html){if("string"==typeof html){var _tempKid=document.createElement("div");this.$els.forEach(function(el){try{el.appendChild(_tempKid),el.insertBefore(_tempKid,el.firstChild),_tempKid.outerHTML=html}catch(err){}})}};esJquery.prototype.get=function $esJquery$$get$(index){if(0===index)return this.$el};
esJquery.prototype.each=function $esJquery$$each$(callback){this.$els.forEach(function(el){callback($es(el))})};esJquery.prototype.text=function $esJquery$$text$(){if(0===arguments.length)return this.$el.textContent;this.$el.textContent=arguments[0];return this};esJquery.prototype.val=function $esJquery$$val$(){if(0===arguments.length)return this.$el.value;this.$el.value=arguments[0];return this};esJquery.prototype.find=function $esJquery$$find$(selector){return new esJquery(this.$el.querySelectorAll(selector))};
esJquery.prototype.append=function $esJquery$$append$(html){if("string"==typeof html){var _tempKid=document.createElement("div");_tempKid.innerHTML=html;this.$els.forEach(function(el){try{el.appendChild(_tempKid)}catch(err){}})}};esJquery.prototype.on=function $esJquery$$on$(evt,sel,handler){this.$el.addEventListener(evt,function(event){for(var t=event.target;t&&t!==this;)t.matches(sel)&&handler.call(t,event),t=t.parentNode});return this};esJquery.prototype.hasClass=function $esJquery$$hasClass$(arg){return this.$el.classList.contains(arg)};
esJquery.prototype.html=function $esJquery$$html$(){var attrArgs=arguments;if(0==attrArgs.length)return this.$el.innerHTML;if(1==attrArgs.length)return this.$el.innerHTML=attrArgs[0],this};esJquery.prototype.getLast=function $esJquery$$getLast$(){return this.$els.length?$es(this.$els[this.$els.length-1]):null};esJquery.prototype.attr=function $esJquery$$attr$(){var attrArgs=arguments;if(1==attrArgs.length)return this.$el.getAttribute(attrArgs[0]);2==attrArgs.length&&this.$els.forEach(function(el){el.setAttribute(attrArgs[0],
attrArgs[1])});return this};esJquery.prototype.remove=function $esJquery$$remove$(){this.$el.remove()};esJquery.prototype.parent=function $esJquery$$parent$(){return $es(this.$el.parentNode)};esJquery.prototype.getEl=function $esJquery$$getEl$(){return this.$el};esJquery.prototype.children=function $esJquery$$children$(){return $es(this.$el.childNodes)};esJquery.prototype.serialize=function $esJquery$$serialize$(){var form=this.$el,query="";if("object"==typeof form&&"FORM"==form.nodeName)for(var i=
0;i<=form.elements.length-1;i++){var field=form.elements[i];if(field.name&&"file"!=field.type&&"reset"!=field.type)if("select-multiple"==field.type)for(var j=0;j<=form.elements[i].options.length-1;j++)field.options[j].selected&&(query+="&"+field.name+"="+encodeURIComponent(field.options[j].value).replace(/%20/g,"+"));else"submit"!=field.type&&"button"!=field.type&&("checkbox"!=field.type&&"radio"!=field.type||field.checked)&&(query+="&"+field.name+"="+encodeURIComponent(field.value).replace(/%20/g,
"+"))}return query.substr(1)};var $es=function $$es$(arg){return new esJquery(arg)};window.es_document_ready=function $window$es_document_ready$(callback){(new Promise(function(resolutionFunc,rejectionFunc){"interactive"!==document.readyState&&"complete"!==document.readyState||resolutionFunc("interactive");document.addEventListener("DOMContentLoaded",function(){resolutionFunc("DOMContentLoaded")},!1);setTimeout(function(){resolutionFunc("timeout")},5E3)})).then(function(resolution){callback(resolution)}).catch(function(err){callback(err)})};
window.es_ajax=function $window$es_ajax$(form_data_pargs){var margs={type:"GET",url:"/",data:{},success:null};form_data_pargs&&(margs=Object.assign(margs,form_data_pargs));var xhr=new XMLHttpRequest;xhr.open(margs.type,margs.url);form_data_pargs=new FormData;for(var key in margs.data)form_data_pargs.append(key,margs.data[key]);xhr.send(form_data_pargs);xhr.addEventListener("load",function handle_loaded(e){200==xhr.status&&margs.success&&margs.success(e,this)})};window.get_query_arg=function $window$get_query_arg$(purl$jscomp$2_regtest,
key){if(-1<purl$jscomp$2_regtest.indexOf(key+"=")&&(purl$jscomp$2_regtest=(new RegExp("[?&]"+key+"(.+?)(?=&|$)")).exec(purl$jscomp$2_regtest),null!=purl$jscomp$2_regtest))return purl$jscomp$2_regtest[1]?purl$jscomp$2_regtest[1].replace(/=/g,""):""};window.add_query_arg=function $window$add_query_arg$(purl$jscomp$3_s,key,value){key=encodeURIComponent(key);value=encodeURIComponent(value);var addition_pair=key+"="+value;purl$jscomp$3_s=purl$jscomp$3_s.replace(new RegExp("(&|\\?)"+key+"=[^&]*"),"$1"+
addition_pair);-1<purl$jscomp$3_s.indexOf(key+"=")||(addition_pair=-1<purl$jscomp$3_s.indexOf("?")?"&"+addition_pair:"?"+addition_pair,purl$jscomp$3_s+=addition_pair);"NaN"==value&&(purl$jscomp$3_s=purl$jscomp$3_s.replace(new RegExp("[?|&]"+key+"="+value),""));return purl$jscomp$3_s};var _esjquery=$es,_constants=__webpack_require__(567),WaveGenerator=function $WaveGenerator$($waveGenerator_){this.initOptions={};this.dataSource="";this.$waveGenerator_=$waveGenerator_;this.$waveGenerator=_esjquery($waveGenerator_);
this.$status=this.$wavedataField=null;this.init()};WaveGenerator.prototype.init=function $WaveGenerator$$init$(){var defaultOptions$jscomp$1_finalOptions={};defaultOptions$jscomp$1_finalOptions=Object.assign({source:"",selectorWaveData:""},{});defaultOptions$jscomp$1_finalOptions=_dzsap_helpers.convertPluginOptionsToFinalOptions(this.$waveGenerator_,defaultOptions$jscomp$1_finalOptions,null,"data-options",_esjquery);var selfClass=this;selfClass.initOptions=defaultOptions$jscomp$1_finalOptions;selfClass.$status=
selfClass.$waveGenerator.find(".dzsap-wave-generator--status");selfClass.initOptions.source&&(selfClass.dataSource=selfClass.initOptions.source);selfClass.initOptions.selectorWaveData&&(selfClass.$wavedataField=_esjquery(selfClass.initOptions.selectorWaveData));selfClass.$status.html("generating waveforms");selfClass.dataSource&&promise_waveGenerate(selfClass.$waveGenerator.find(".dzsap-wave-generator--wave").get(0),selfClass.dataSource).then(function(resolve){selfClass.$status.html("");try{if(resolve.pcm_data&&
selfClass.$wavedataField){selfClass.$wavedataField.val(resolve.pcm_data);var JSCompiler_temp;if(JSCompiler_temp="on"===dzsap_settings.dzsap_wave_generate_auto){a:{var purl=window.location.href;if(-1<purl.indexOf("dzsap_wave_generate_auto=")){var regtest=/[?&]dzsap_wave_generate_auto=.+/.exec(purl);if(null!=regtest){var splitterS=regtest[0];-1<splitterS.indexOf("&")&&(splitterS=splitterS.split("&")[1]);var JSCompiler_inline_result=splitterS.split("=")[1];break a}}JSCompiler_inline_result=void 0}JSCompiler_temp=
"on"===JSCompiler_inline_result}JSCompiler_temp&&window.dzsap_admin_waveforms_submitPcmData(document.querySelector(".track-waveform-meta"))}}catch(err){console.log(err)}})};window.es_document_ready(function(){_esjquery(".dzsap-wave-generator.auto-init").each(function($el){new WaveGenerator($el.get(0))})});window.dzsap_generating_pcm=!1;var promise_waveGenerate=function $promise_waveGenerate$($container_,sourceMp3,pargs){var margs;return $jscomp.asyncExecutePromiseGeneratorProgram(function($jscomp$generator$context){margs=
Object.assign({called_from:"default",preferBackendPeaks:!0,wavesurfer_pcm_length:200},pargs);return $jscomp$generator$context.return(new Promise(function(resolvePcm,rejectPcm){(function wavesurfer_renderPcm(){function asyncRenderPcm(resolve,reject){if(window.dzsap_generating_pcm)return setTimeout(function(){asyncRenderPcm(resolve,reject)},1E3),!1;window.dzsap_generating_pcm=!0;var wavesurferConId="wavesurfer_"+Math.ceil(1E4*Math.random());$container_||($container_=document.body);_esjquery($container_).append('<div id="'+
wavesurferConId+'"></div>');var linGrad=document.createElement("canvas").getContext("2d").createLinearGradient(0,64,0,200);linGrad.addColorStop(.5,"rgb(107,95,95)");linGrad.addColorStop(.5,"rgb(119,115,115)");var wavesurfer=WaveSurfer.create({container:"#"+wavesurferConId,normalize:!0,pixelRatio:1,waveColor:linGrad,progressColor:"hsla(200, 100%, 30%, 0.5)",cursorColor:"#fff",barWidth:2});wavesurfer.on("loading",function(percents){$container_.parentNode.querySelector(".dzsap-wave-generator--status").innerHTML=
percents+"%"});try{wavesurfer.load(sourceMp3)}catch(err){console.log("[wavesurfer] WAVE SURFER NO LOAD")}wavesurfer.on("ready",function(){console.log("[dzsap] [wavesurfer] generating wave data for ",sourceMp3);var pcmDataArr=[],pcmDataString="";if(wavesurfer&&wavesurfer.exportPCM){!0!==margs.preferBackendPeaks&&(pcmDataArr=wavesurfer.exportPCM(margs.wavesurfer_pcm_length,100,!0));var isPcmDataArrValid=!1;try{pcmDataArr=JSON.parse(pcmDataString);for(var i in pcmDataArr)if(null!==pcmDataArr[i]&&0!==
pcmDataArr[i]&&"0"!==pcmDataArr[i]){isPcmDataArrValid=!0;break}}catch(err$0){isPcmDataArrValid=!1}isPcmDataArrValid||(pcmDataArr=wavesurfer.backend.getPeaks(margs.wavesurfer_pcm_length,0,margs.wavesurfer_pcm_length));for(var i$1 in pcmDataArr)null!==pcmDataArr[i$1]&&0!==pcmDataArr[i$1]&&"0"!==pcmDataArr[i$1]&&(pcmDataArr[i$1]=Math.abs(Number(Number(pcmDataArr[i$1]).toFixed(2))))}else pcmDataArr=_dzsap_helpers.generateFakeArrayForPcm();pcmDataString=JSON.stringify(pcmDataArr);resolve({resolve_type:"success",
pcm_data:pcmDataString})});wavesurfer.on("error",function(err,err2){reject({error_type:"wavesurfer_error",error_message:err})});setTimeout(function(){reject({error_type:"wavesurfer_timeout",error_message:"timeout"})},_constants.OF.WAVESURFER_MAX_TIMEOUT)}return $jscomp.asyncExecutePromiseGeneratorProgram(function($jscomp$generator$context$1){return $jscomp$generator$context$1.return(new Promise(function(resolve,reject){asyncRenderPcm(resolve,reject)}))})})().then(function(responsePcm){console.log("%c [dzsap] [wave] success while generating pcm - ",
_constants.OF.DEBUG_STYLE_PLAY_FUNCTIONS,responsePcm);resolvePcm(responsePcm)}).catch(function(err){for(var default_pcm=[],i3=0;200>i3;i3++)default_pcm[i3]=Math.abs(Number(Math.random()).toFixed(2));default_pcm=JSON.stringify(default_pcm);console.log("%c [dzsap] [wave] error while generating pcm - ",_constants.OF.DEBUG_STYLE_PLAY_FUNCTIONS,err,err.error_message);resolvePcm(default_pcm)})}))})}}()})();}).call(this || window)
